#--------------------
# Burp.toml
#
# This is the official Burp.toml for the Burp deployment tool. You can reference this
# to see how a Burp.toml would appear.
#---------------------
version = 1.0

#------------
# NOTE: When using `bind` with files that only exist on the client-side
# e.g. private configuration files, make sure to use the `.burpy/home/` parent
# folder since Burp drops all the files from `includes` to that directory.
#
# It is recommended to link that directory with burp using
# { type = "bind", source = "path/to/host/folder", target = ".burpy/home/` }
#--------------
includes = [
    { source = "data/git.toml", target = "data/git.toml" },
    { source = "data/docker.toml", target = "data/docker.toml" },
]

[service]
name = "burp"
build = "/"
repository = "https://github.com/ShindouMihou/burp"
restart_policy = { name = "always" }
volumes = [
    { type = "bind", source = "/data/burp/", target = ".burpy/home/"},
    { type = "bind", source = "/var/run/docker.sock", target = "/var/run/docker.sock" }
]
ports = [["8837","8873"]]

#-------------------------------
# Burp will use the `burp.env` file as its base for the final `.env` output.
# To configure burp, remember to rename the `.env.example` into `burp.env` and
# configure from there.
#-------------------------------
[environment]
file = "burp.env"
output = ".env"