# Version is an indicator of the recommended version of burper to use
# for this application.
version = 1.0

[service]
name = "burp"
build = "."

[[dependencies]]
name = "redis"
image = "redis"
command = "redis-server  --appendonly  yes --requirepass \"[burp: Random(12) AS redis_pass]\""
ports = [[6379,6379]]

[dependencies.environment]
REDIS_PASSWORD="[burp: Use(redis_pass)]"

[environment]
file = "[burp].env"
output = ".env"

[environment.replacements]
# There are functions that can accept calls to another function, to call another function as an argument
# of a function, you have to do it such as below:
REDIS_PASSWORD_HASHED="[burp: Hash(burp: Use(redis_pass))]"
REDIS_URI="redis://root:[burp: Use(redis_pass)]@172.17.0.1:6379"
REDIS_CONCAT_TEST="[burp: Concat(burp: Use(redis_pass), ,burp: Random(4) AS ran, ,burp: Hash(burp:Use(ran)))]"