#--------------------
# Burp.toml
#
# Temporarily, this doesn't serve as a proper Burp.toml, but somewhat
# similar. It serves more of a demonstration of what Burp can achieve.
#
# A proper Burp.toml will be created once Burp is ready, it will then be used
# in the future for Burp deployments.
#---------------------
version = 1.0

[service]
name = "burp"
build = "."
repository = "https://github.com/ShindouMihou/burp"

[[dependencies]]
name = "redis"
image = "redis"
command = "redis-server  --appendonly  yes --requirepass \"[burp: Random(12) AS redis_pass]\""
ports = [[6379,6379]]

[dependencies.environment]
REDIS_PASSWORD="[burp: Use(redis_pass)]"

[environment]
file = "[burp].env"
output = ".env"

[[calls]]
IGNORE_1="[burp: Store(hello,world)]"
IGNORE_2="[burp: Store(world,hello)]"

[environment.replacements]
REDIS_URI="redis://root:[burp: Use(redis_pass)]@172.17.0.1:6379"

# These are intended to test different functions
# to see if they function as properly.
HASH_TEST="[burp: Hash(burp: Use(redis_pass))]"
CONCAT_TEST="[burp: Concat(burp: Use(redis_pass), ,burp: Random(4) AS ran, ,burp: Hash(burp:Use(ran)))]"
ADDITION_TEST="[burp: Add(1,1,5,5)]"
SUBTRACTION_TEST="[burp: Sub(2,1)]"
MULTIPLICATION_TEST="[burp: Mpy(2,2)]"
DIVISION_TEST="[burp: Div(2,2)]"
MODULO_TEST="[burp: Mod(2,2)]"
RANDOM_NUMBER_TEST="[burp: RandN(500)]"
STORE_TEST="[burp: Concat(burp: Use(hello), , burp: Use(world))]"