#--------------------
# Burp.toml
#
# This current file serves as a demonstration file of a proper Burp.toml file.
# The file is what Primrose (https://github.com/ShindouMihou/primrose) would use
# when it becomes Burp-compatiable.
#
# Proven and tested via testing.
#---------------------
version = 1.0

[service]
name = "primrose-backend"
build = "core/"
repository = { link = "https://github.com/ShindouMihou/primrose" }
restart_policy = { name = "always" }

[[dependencies]]
name = "primrose-mongo"
image = "mongo"
ports = [["2732","27017"]]
restart_policy = { name = "always" }
networks = ["mongo"]
volumes = [
    { type = "volume", source = "primrose_data", target = "/data/db" }
]

[dependencies.environment]
MONGO_INITDB_ROOT_USERNAME="root"
MONGO_INITDB_ROOT_PASSWORD="[burp: Random(256) AS mongo.password]"

#--------------------------
# In this example, we have enabled server-side translations for .env file.
# And it's primarily because, we are generating our own credentials using the `environment.replacements`
# of Burp which enables us to create our own credentials safely, even allowing argon2id hashes.
#
# But in most cases, unless you don't need to know the secrets, you should most likely use the
# client-side translations.
#-------------------------
[environment]
baseline = "core/.env.example"
override = false
server-side = true

[environment.replacements]
MONGO_URI="mongodb://root:[burp: Use(mongo.password)]@172.17.0.1:2732"
SIGNING_KEY="[burp: Random(256)]"

[[volumes]]
name="mongo"