#--------------------
# Burp.toml
#
# This current file serves as a demonstration file of a proper Burp.toml file.
# The file is what Primrose (https://github.com/ShindouMihou/primrose) would use
# when it becomes Burp-compatiable.
#
# Proven and tested via testing.
#---------------------
version = 1.0

#------------
# NOTE: When using `bind` with files that only exist on the client-side
# e.g. private configuration files, make sure to use the `.burpy/home/` parent
# folder since Burp drops all the files from `includes` to that directory.
#
# It is recommended to link that directory with burp using
# { type = "bind", source = "path/to/host/folder", target = ".burpy/home/` }
#--------------
includes = [
    { source = "data/git.toml", target = "data/get.toml", required = false },
    { source = "data/docker.toml", target = "data/docker.toml", required = false },
]

[service]
name = "primrose_core"
build = "core/"
repository = "https://github.com/ShindouMihou/primrose"
restart_policy = { name = "always" }

[[dependencies]]
name = "mongo"
image = "mongo"
ports = [["2732","27017"]]
restart_policy = { name = "always" }
networks = ["mongo"]
volumes = [
    { type = "volume", source = "primrose_data", target = "/data/db" }
]

[dependencies.environment]
MONGO_INITDB_ROOT_USERNAME="root"
MONGO_INITDB_ROOT_PASSWORD="[burp: Random(256) AS mongo.password]"

[environment]
file = "core/.env.example"
output = "core/.env"

[environment.replacements]
MONGO_URI="mongodb://root:[burp: Use(mongo.password)]@172.17.0.1:2732"
SIGNING_KEY="[burp: Random(256)]"

[[volumes]]
name="mongo"